name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Firebase Credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > /tmp/firebase-adminsdk.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "Setting GOOGLE_APPLICATION_CREDENTIALS environment variable"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-adminsdk.json

      - name: Build with Maven
        run: mvn clean install -DskipTests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet
